test:
  modifications:
    - with sunglasses

default: &default
  modifications:
    - cartoon line drawing
    - van gogh
    - dali
    - watercolour
    - black and white
    - ink
    - pencil
    - checkered
    - close-up
    - crazy
    - googly eyes
    - surprised
    - upside down
    - dancing
    - vermeer
    - in a museum
    - in space
    - cave painting
    - on a t shirt
    - punk
    - tie dye
    - sunny
    - dusk
    - campfire
    - circled
    - inverted colours
    - swirl effect

development:
  <<: *default

production:
  <<: *default
